/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "data": string;
        "height": number;
        "width": number;
    }
    interface OcsDockedBoxes {
        "data": string;
        "drawChart": () => Promise<void>;
    }
    interface OcsNativeDockedBoxes {
        "data": string;
        "getCanvasSize": () => Promise<void>;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLOcsDockedBoxesElement extends Components.OcsDockedBoxes, HTMLStencilElement {
    }
    var HTMLOcsDockedBoxesElement: {
        prototype: HTMLOcsDockedBoxesElement;
        new (): HTMLOcsDockedBoxesElement;
    };
    interface HTMLOcsNativeDockedBoxesElement extends Components.OcsNativeDockedBoxes, HTMLStencilElement {
    }
    var HTMLOcsNativeDockedBoxesElement: {
        prototype: HTMLOcsNativeDockedBoxesElement;
        new (): HTMLOcsNativeDockedBoxesElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "ocs-docked-boxes": HTMLOcsDockedBoxesElement;
        "ocs-native-docked-boxes": HTMLOcsNativeDockedBoxesElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "data"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface OcsDockedBoxes {
        "data"?: string;
    }
    interface OcsNativeDockedBoxes {
        "data"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "ocs-docked-boxes": OcsDockedBoxes;
        "ocs-native-docked-boxes": OcsNativeDockedBoxes;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "ocs-docked-boxes": LocalJSX.OcsDockedBoxes & JSXBase.HTMLAttributes<HTMLOcsDockedBoxesElement>;
            "ocs-native-docked-boxes": LocalJSX.OcsNativeDockedBoxes & JSXBase.HTMLAttributes<HTMLOcsNativeDockedBoxesElement>;
        }
    }
}
